---
step-runner-config:
  global-defaults:
    application-name: ref-quarkus-mvn-jenkins-typ

  deploy:
  - implementer: ArgoCD
    config:
      deployment-config-repo: http://gitea.tssc.rht-set.com/ploigos-reference-applications/reference-quarkus-mvn-cloud-resources_jenkins_workflow-typical.git
