---
step-runner-config:
  config-decryptors:
  - implementer: SOPS

  global-defaults:
    organization: ploigos-ref
    service-name: fruit

    maven-servers:
      nexus.apps.tssc.rht.set.com:
        id: nexus.apps.tssc.rht.set.com
        username: sa-ploigos-ref-apps
    maven-mirrors:
      nexus.apps.tssc.rht.set.com:
        id: nexus.apps.tssc.rht.set.com
        url: https://nexus.apps.tssc.rht-set.com/repository/maven-public/
        mirror-of: '*'
    container-registries:
        registry.redhat.io:
            username: 6340056|tssc-integration-infra
        registry-internal-nexus.apps.tssc.rht-set.com:
            username: sa-ploigos-ref-apps

  tag-source:
  - implementer: Git
    config:
      git-username: sa-ploigos-ref-apps

  unit-test:
  - implementer: MavenTest

  package:
  - implementer: MavenPackage

  static-code-analysis:
  - implementer: SonarQube
    config:
      url: https://sonarqube-sonarqube.apps.tssc.rht-set.com/
      username: reference-apps-sa

  push-artifacts:
  - implementer: MavenDeploy
    config:
      maven-push-artifact-repo-id: nexus.apps.tssc.rht.set.com
      maven-push-artifact-repo-url: https://nexus.apps.tssc.rht-set.com/repository/reference-apps/

  create-container-image:
  - implementer: Buildah

  push-container-image:
  - implementer: Skopeo
    config:
      destination-url: registry-internal-nexus.apps.tssc.rht-set.com

  sign-container-image:
  - implementer: PodmanSign
    config:
      container-image-signature-destination-url: http://artifactory.apps.tssc.rht-set.com/artifactory/container-image-signatures
      container-image-signature-destination-username: tssc

  container-image-static-vulnerability-scan:
  - name: OpenSCAP - Vulnerability - DataStream
    implementer: OpenSCAP
    config:
      oscap-input-definitions-uri: https://www.redhat.com/security/data/metrics/ds/v2/RHEL8/rhel-8.ds.xml.bz2
      oscap-tailoring-uri: https://raw.githubusercontent.com/ploigos-reference-apps/ploigos-example-oscap-content/main/xccdf_com.ploigos_profile_default_cve_ploigos_reference_apps-tailoring.xml
      oscap-profile: xccdf_com.ploigos_profile_default_cve_ploigos_reference_quarkus_mvn

  deploy:
  - implementer: ArgoCDDeployDeploy
    config:
      argocd-api: argocd-server-argocd.apps.tssc.rht-set.com
      argocd-username: admin
      argocd-skip-tls: True
      deployment-config-helm-chart-path: charts/reference-quarkus-mvn-deploy
      deployment-config-helm-chart-values-file-image-tag-yq-path: 'image.tag'
      git-email: 'ploigos+it@redhat.com'
      argocd-sync-timeout-seconds: 130
    environment-config:
      DEV:
        deployment-config-helm-chart-environment-values-file: values-DEV.yaml
      TEST:
        deployment-config-helm-chart-environment-values-file: values-TEST.yaml
      PROD:
        deployment-config-helm-chart-environment-values-file: values-PROD.yaml

  validate-environment-configuration:
  - implementer: ConfiglintFromArgocd
  - implementer: Configlint
    config:
      rules: cicd/ValidateEnv/

  uat:
  - implementer: MavenIntegrationTest
    config:
      target-host-url-maven-argument-name: 'target.base.url'
      maven-additional-arguments:
       - -Dselenium.hub.url=http://67.207.93.102:4444
      additional-artifacts-dirs:
      - name: cucumber-reports
        path: 'target/cucumber-reports'

  report:
  - implementer: ResultArtifactsArchive
    config:
      results-archive-destination-url: https://nexus.apps.tssc.rht-set.com/repository/release-engineering-workflow-result-artifacts-archives/
      results-archive-destination-username: sa-ploigos-ref-apps
